baseURL = "https://uber.day"
languageCode = "en-us"
removePathAccents = true
theme = "infinity-hugo"
title = "Uber.Day - A Cypto Wallet"
[params]
customHead = ""
[params.about]
description = "Uber.day is created to host a crypto wallet enabling easy crypto transacations and communcations"
enable = true
heading = "Uber.day- An Easy Crypto Wallet"
[[params.about.sliderItem]]
image = "images/about/1.jpg"
[params.contact]
enable = true
subtitle = "Contact us"
title = "Get In Touch"
[params.cta]
bg = "images/call-to-action.jpg"
enable = false
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
title = "Subscribe to our mailing list"
[params.hero]
bg = "images/header-bg.jpg"
countdownDay = "31"
countdownMonth = "12"
countdownYear = "2022"
disableCountdown = false
enable = true
subtitle = "Meanwhile, Did you know that you can send us Crypto directly to this website? Send us your cypto today to: uber.day"
title = "Uber Cool Days Are Coming Soon!"
[params.navigation]
about = "About"
contact = "Contact"
home = "Home"
logo = "images/Uber_day-logos__white_18.png"
service = "Services"
[params.service]
enable = false
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"
title = "Find Better Solutions Build Better Products"
[[params.service.serviceItem]]
delay = "0s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "0.6s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
[[params.service.serviceItem]]
delay = "0.8s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "1s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "1.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "1.5s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
